### ISSUE TITLE
NotFoundException: The specified job template was not found: jobTemplateArn

### ISSUE THREAD

**Issue by SabyasachiRana** [awslabs/video-on-demand-on-aws#122] opened 2020-12-20 13:54 UTC
I'm Using Latest 5.2.0 and I got that Error 
This template Working in UI
The specified job template was not found: jobTemplateArn=arn:aws:mediaconvert:us-east-1:001235567890:jobTemplates/test_Ott_2160p_hevc_aac_16x9_mvod_no_preset."

"    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",         "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",         "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",         "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",         "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",         "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",         "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",         "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",         "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",         "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"     ] } | 2020-12-20T10:03:22.703Z b70ef776-1da1-4bbf-834a-8e85c98198e8 ERROR Invoke Error {"errorType":"NotFoundException","errorMessage":"The specified job template was not found: jobTemplateArn=arn:aws:mediaconvert:us-east-1:001235567890:jobTemplates/ranaott4_Ott_2160p_hevc_aac_16x9_mvod_no_preset.","code":"NotFoundException","message":"The specified job template was not found: jobTemplateArn=arn:aws:mediaconvert:us-east-1:001235567890:jobTemplates/test_Ott_2160p_hevc_aac_16x9_mvod_no_preset.","time":"2020-12-20T10:03:20.729Z","requestId":"c087cf03-0f46-4d92-8320-acb539a32697","statusCode":404,"retryable":false,"retryDelay":42.95868933566853,"stack":["NotFoundException: The specified job template was not found: jobTemplateArn=arn:aws:mediaconvert:us-east-1:001235567890:jobTemplates/test_Ott_2160p_hevc_aac_16x9_mvod_no_preset."," at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)"," at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)"," at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)"," at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)"," at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)"," at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)"," at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)"," at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10"," at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)"," at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"]}
-- | --

**Comment by SabyasachiRana** [comment] 2020-12-20 13:58
@tomnight Can You Please help?

**Comment by morjoan** [comment] 2021-01-25 19:59
Hi there, 
I am unable to reproduce the issue you are seeing. 

Is the job being triggered via a Metadata file? If so, please make sure that you refer to the jobTemplate exactly as it shown in the MediaConvert UI template page. Template names are case sensitive.

**Comment by tomgilman** [comment] 2021-02-15 18:08
Closing this for now as we're not able to reproduce.

**Closed by tomgilman** 2021-02-15 18:08 UTC
Labels: bug
