### ISSUE TITLE
Slow processing workflow

### ISSUE THREAD

**Issue by mpassante** [awslabs/video-on-demand-on-aws#72] opened 2020-04-12 21:55 UTC
Hi, I want allow users of my app to load their videos on my severs and allow streaming of these. In order to convert these videos, I am using aws video on demand with custom template. I load on S3 video to convert and manifest.json, but I am experiencing really a big slowness in all workflow.
When a new video (max 15 secs) is added to the source Amazon Simple Storage Service (Amazon S3) bucket, an AWS Lambda function starts the ingest step function. The ingest step function includes:
1) STEP FUNCTION (Duration: 1238.64 msec)
2) INPUT VALIDATOR   (Duration: 1269.10 ms)
3) MEDIA INFO (Duration: 3180.28 ms)
4) DINAMO UPDATE (Duration: 1210.68 ms)
5) SNS NOTIFICATION  (Duration: 1212.05 ms)
6) STEP FUNCTION (Duration: 148.47 ms)

When the ingest workflow is complete, it starts the processing workflow. The processing workflow includes:
1) PROFILE (Duration: 1266.55 ms)
2) ENCODE (Duration: 1668.10 ms)
3) DINAMO  UPDATE (Duration: 151.84 ms)

Then AWS Media convert receive into queue the job and sometimes it wait 2-5 secs before start execution. Sometimes timing to wait into queue can also be greater than 60 secs, but queue is empty (contains only my job). Aceleration is diasabled, priority is set to 0 and I am using default queue (on demand). Process of encoding is around 5 secs.

After the video is encoded, a third Step Functions workflow validates the output and file metadata is stored in Amazon DynamoDB:
1) STEP FUNCTION (Duration: 116.62 ms)
2) OUTPUT VALIDATOR  (Duration: 1159.43 ms)
3) DINAMO UPDATE(Duration: 198.01 ms)

Last operation sends an Amazon SNS notification with a summary of the workflow and the Amazon CloudFront URLs:
4) SNS NOTIFICATION  (Duration: 116.06 ms)

As you can see, for a video of max 15 secs, (these timing are taken loading a video of 10 sec) an user could wait around 30 secs ( + timing to upload video on S3) before it is avalaible for streaming. Performance are really bad.What is the wrong in this solution? It is possible reduce slowness of workflow?
Thanks

**Comment by tomnight** [comment] 2020-05-08 15:45
Sorry for the late response on this. 

The solution wasn't designed with this specific use case in mind but more for processing large video archives and large video formats.  If speed is important and you don't need all the functionality of the solution then I would suggest you just take the parts of the work flow that you need and build a your own. 

For example the profiler step check the resolution of the source video based on the output from mediainfo and defines which of the 3 encoding templates to use. If you have a consistant input you may not need this step. The templates create 3 outputs by default including HLS, DASH and MP4; do you need all of the  outputs and all of the bit-rates? stripping down the number outputs and bit rates will reduce the encoding time. 

Hope this helps

**Comment by tomnight** [comment] 2020-06-01 18:27
Closing as this not a bug but we will take the feedback into consideration in the next release 

Thanks

**Closed by tomnight** 2020-06-01 18:27 UTC
